connections = 
{

    /chip_spi/chip_spi_ctl/S_AXI
    /framegen/framegen_ctl/S_AXI
    /indy_power_ctl/S_AXI
    /adc_bank/axi_adc_bank/S_AXI
    /indy_lvds/lvds_ctl/S_AXI                                   bdc/sources_1/bd/indy_lvds/src/lvds_ctl.v  LVDS



    /abm_and_smem/abm_and_smem_ctl/S_AXI                        bdc/sources_1/bd/abm_and_smem/src/abm_and_smem_ctl.v         REG 
    /adc_bank/axi_adc_bank/S_AXI                                project/src/ltc1867/axi_adc_bank.v                           REG
    /chip_power/indy_power_ctl/S_AXI                            project/src/indy_power_ctl.v                                 REG
    /lvds/fake_lvds_ctl/S_AXI                                   bdc/sources_1/bd/lvds/src/fake_lvds_ctl.v                    LVDS 
    /mindy_core/mindy_core_ctl/S_AXI                            bdc/sources_1/bd/mindy_core/src/mindy_core_ctl.v             MC 
    /abm_and_smem/chipif_cdc/clock_manager/clock_mgr_ctl/S_AXI  bdc/sources_1/bd/abm_and_smem/src/clock_mgr/clock_mgr_ctl.v  CHIP
}


